import { writeFileSync } from 'node:fs';
import { applyAction, createGame } from '../src/game';
import { pickAIAction } from '../src/ai';
import { getBoard } from '../src/geometry';
import type { Difficulty, ShapeId } from '../src/types';

const SHAPES: ShapeId[] = ['triangle'];
const LEVELS: Difficulty[] = [1, 2, 3, 4];
const N = 100;

interface CellResult {
  p1Wins: number;
  p2Wins: number;
  draws: number;
  avgP1: number;
  avgP2: number;
}

function simulateOne(shape: ShapeId, p1: Difficulty, p2: Difficulty) {
  let state = createGame(shape, 'ai', p1);
  while (!state.finished) {
    const lvl = state.current === 1 ? p1 : p2;
    const action = pickAIAction(state, lvl, state.current);
    state = applyAction(state, action);
  }
  return { winner: state.winner, s1: state.scores[1], s2: state.scores[2] };
}

function runCell(shape: ShapeId, p1: Difficulty, p2: Difficulty): CellResult {
  let p1Wins = 0;
  let p2Wins = 0;
  let draws = 0;
  let sumP1 = 0;
  let sumP2 = 0;
  for (let i = 0; i < N; i++) {
    const r = simulateOne(shape, p1, p2);
    sumP1 += r.s1;
    sumP2 += r.s2;
    if (r.winner === 1) p1Wins++;
    else if (r.winner === 2) p2Wins++;
    else draws++;
  }
  return {
    p1Wins,
    p2Wins,
    draws,
    avgP1: sumP1 / N,
    avgP2: sumP2 / N,
  };
}

function formatPct(n: number): string {
  return `${n.toString().padStart(3, ' ')}%`;
}

function buildShapeSection(shape: ShapeId): { md: string; matrix: CellResult[][] } {
  const board = getBoard(shape);
  const matrix: CellResult[][] = [];

  let md = `## ${shape[0].toUpperCase() + shape.slice(1)} (${board.dots.length} dots, ${board.lines.length} scoring lines)\n\n`;
  md += `Cell format: **P1 wins / draws / P2 wins** out of ${N} games. Avg scores below in parentheses.\n\n`;
  md += `| P1 \\ P2 | L1 | L2 | L3 | L4 |\n`;
  md += `|---|---|---|---|---|\n`;

  for (const p1 of LEVELS) {
    const row: CellResult[] = [];
    const cells: string[] = [];
    process.stdout.write(`  P1=L${p1}: `);
    for (const p2 of LEVELS) {
      const t0 = Date.now();
      const res = runCell(shape, p1, p2);
      const ms = Date.now() - t0;
      row.push(res);
      cells.push(
        `${formatPct(res.p1Wins)} / ${formatPct(res.draws)} / ${formatPct(res.p2Wins)}<br/>(avg ${res.avgP1.toFixed(1)} vs ${res.avgP2.toFixed(1)})`
      );
      process.stdout.write(`L${p2}(${ms}ms) `);
    }
    process.stdout.write('\n');
    matrix.push(row);
    md += `| **L${p1}** | ${cells.join(' | ')} |\n`;
  }

  md += `\n`;
  return { md, matrix };
}

function buildConclusions(shape: ShapeId, matrix: CellResult[][]): string {
  let md = `## Conclusions — ${shape}\n\n`;

  md += `### P1 plays optimally (L4)\n\n`;
  md += `Win rate of L4-as-P1 vs each opponent level:\n\n`;
  const p1Row = matrix[3];
  LEVELS.forEach((lvl, i) => {
    const c = p1Row[i];
    md += `- vs **L${lvl}**: **${c.p1Wins}%** wins · ${c.draws}% draws · ${c.p2Wins}% losses (avg ${c.avgP1.toFixed(1)} – ${c.avgP2.toFixed(1)})\n`;
  });

  md += `\n### P2 plays optimally (L4)\n\n`;
  md += `Win rate of L4-as-P2 vs each opponent level:\n\n`;
  LEVELS.forEach((lvl, i) => {
    const c = matrix[i][3];
    md += `- vs **L${lvl}**: **${c.p2Wins}%** wins · ${c.draws}% draws · ${c.p1Wins}% losses (avg ${c.avgP1.toFixed(1)} – ${c.avgP2.toFixed(1)})\n`;
  });

  md += `\n### First-mover advantage (same-level diagonal)\n\n`;
  LEVELS.forEach((lvl, i) => {
    const c = matrix[i][i];
    const adv = c.p1Wins - c.p2Wins;
    const sign = adv > 0 ? `**+${adv}** for P1` : adv < 0 ? `**${adv}** for P1 (i.e. P2 favored)` : `dead even`;
    md += `- **L${lvl} vs L${lvl}**: P1 ${c.p1Wins}% · draws ${c.draws}% · P2 ${c.p2Wins}% → ${sign}\n`;
  });

  md += `\n### Overall observations\n\n`;
  const l4l4 = matrix[3][3];
  md += `- Best-vs-best (L4 vs L4) gives the cleanest answer to "no-mistakes probability": P1 ${l4l4.p1Wins}%, draws ${l4l4.draws}%, P2 ${l4l4.p2Wins}%.\n`;
  const l4l1 = matrix[3][0];
  md += `- L4 dominates L1 with ${l4l1.p1Wins}% wins as P1; L1 as P1 beats L4 with ${matrix[0][3].p1Wins}% wins (the rest are L4-as-P2 wins or draws).\n`;
  md += `- Sample size N=${N} per cell → typical 95% confidence ±10 percentage points for win-rate estimates.\n`;

  md += `\n`;
  return md;
}

function main() {
  const tStart = Date.now();
  let body = `# AI Simulation Results\n\nGenerated by \`npm run simulate\`. Sample size: **N = ${N} games per cell**.\n\nAI levels: L1=Beginner (random + corners + big-wins) · L2=Easy (greedy) · L3=Medium (1-ply minimax) · L4=Hard (2-ply minimax).\n\n`;

  for (const shape of SHAPES) {
    console.log(`\n=== Simulating ${shape} ===`);
    const { md, matrix } = buildShapeSection(shape);
    body += md;
    body += buildConclusions(shape, matrix);
    console.log(md);
  }

  const tEnd = Date.now();
  body += `---\n\nTotal runtime: ${((tEnd - tStart) / 1000).toFixed(1)}s.\n`;

  writeFileSync('simulation-results.md', body, 'utf8');
  console.log(`\nWritten simulation-results.md (${body.length} bytes)`);
  console.log(`Total: ${((tEnd - tStart) / 1000).toFixed(1)}s`);
}

main();
